export enum BroadcastType {
  BANK_DATA_UPDATED = "BANK_DATA_UPDATED",
  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_DELETED = "SUBSCRIPTION_DELETED",
}
