export enum BroadcastType {
  // STRIPE SUBSCRIPTIONS ACTIONS for web
  BANK_DATA_UPDATED = "BANK_DATA_UPDATED",
  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_DELETED = "SUBSCRIPTION_DELETED",

  // APPLE SUBSCRIPTION ACTIONS for Ios App
  APPLE_SUBSCRIPTION_UPDATED = "APPLE_SUBSCRIPTION_UPDATED",
  OWNERS_APPLE_SUBSCRIPTION_ENDED = "OWNERS_APPLE_SUBSCRIPTION_ENDED",

  // TRANSACTIONS ACTIONS
  TRANSACTION_CREATED = "TRANSACTION_CREATED",
}
